version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build step...
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build/
