name: CI/CD Pipeline

on:
  push:
    branches:
      - main # events to the main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # virtual machine

    steps:

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client  
         
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        services=("api-gateway" "account-service" "wallet-service" "trading-service")
        for service in "${services[@]}"; do
          docker build -t dilshan1/$service:latest ./$service
          docker push dilshan1/$service:latest
        done

    # - name: Set up Kubernetes CLI
    #   uses: azure/setup-kubectl@v1
    #   with:
    #     version: '1.24.0'
    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest' # or a specific version like '1.26.0'

    - name: Create Kubernetes directory structure
      run: |
        mkdir -p kubernetes/green
        echo "Created kubernetes/green directory"
        ls -R kubernetes
      
    - name: Create sample deployment files
      run: |
        for service in trading wallet account-management api-gateway; do
          cat <<EOF > kubernetes/green/${service}-deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${service}
          namespace: green
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${service}
            template:
              metadata:
              labels:
                app: ${service}
              spec:
                containers:
                - name: ${service}
                  image: dilshan1/${service}:latest
                  ports:
                  - containerPort: 80
          EOF
            echo "Created ${service}-deployment.yaml"
          done
          ls -l kubernetes/green

    - name: Deploy to Green Environment
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/green/trading-deployment.yaml
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/green/wallet-deployment.yaml
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/green/account-management-deployment.yaml
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/green/api-gateway-deployment.yaml

    - name: Wait for rollouts
      run: |
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/trading -n green
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/wallet -n green
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/account-management -n green
        kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/api-gateway -n green

    - name: Run unit tests
      run: |
        services=("api-gateway" "account-service" "wallet-service" "trading-service")
        for service in "${services[@]}"; do
          cd $service
          pip install -r requirements.txt
          pytest
          cd ..
        done

    - name: Run integration tests
      run: |
        ./test_integration.sh

    - name: Run migrations
      run: |
        services=("trading-service" "wallet-service" "account-management-service")
        for service in "${services[@]}"; do
          cd $service
          if [ -f "migrations" ]; then
            flask db upgrade # For Flask-Migrate
          elif [ -f "scripts/migrate-db.sh" ]; then
            ./scripts/migrate-db.sh
          fi
          cd ..
        done

    - name: Switch Traffic to Green
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f kubernetes/services.yaml # Update Service to point to Green
        kubectl --kubeconfig=kubeconfig.yaml delete namespace blue # Optional: clean up Blue namespace

    - name: Clean up
      run: |
        rm -f kubeconfig.yaml

        
